### ISSUE TITLE
NullPointerException при вызове метода getTradableSharesSync()/getAllSharesAsync

### ISSUE THREAD

**Issue by abubakirov** [Tinkoff/investAPI#185]
Программа на Java:

    public static void main(String[] args) throws InterruptedException {
        var shares = api.getInstrumentsService().getAllSharesSync();
    }

Выдает ошибку:

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.HashMap.get(Object)" because the return value of "java.util.Map.get(Object)" is null
	at ru.tinkoff.piapi.core.utils.Helpers.getErrorDescription(Helpers.java:153)
	at ru.tinkoff.piapi.core.utils.Helpers.apiRuntimeException(Helpers.java:52)
	at ru.tinkoff.piapi.core.utils.Helpers.unaryCall(Helpers.java:45)
	at ru.tinkoff.piapi.core.InstrumentsService.getSharesSync(InstrumentsService.java:461)
	at ru.tinkoff.piapi.core.InstrumentsService.getTradableSharesSync(InstrumentsService.java:475)

**Comment by hondasmx** [comment]
Добрый день!
Ошибка, вероятно, возникает, потому что SDK получает неверный код ошибки. 
Есть ли возможность подебажить SDK (ru.tinkoff.piapi.core.utils.Helpers#getErrorId) и показать, что прилетает?
