### ISSUE TITLE
помогите, ошибка в запросах

### ISSUE THREAD

**Issue by dokisbro** [Tinkoff/investAPI#439]
error: invalid json response body at https://api-invest.tinkoff.ru/openapi/sandbox/market/candles?from=2023-06-03T08%3A24%3A47.355Z&to=2023-06-09T20%3A59%3A00.000Z&figi=BBG004RVFFC0&interval=hour reason: Unexpected end of JSON input
FetchError: invalid json response body at https://api-invest.tinkoff.ru/openapi/sandbox/market/candles?from=2023-06-03T08%3A24%3A47.355Z&to=2023-06-09T20%3A59%3A00.000Z&figi=BBG004RVFFC0&interval=hour reason: Unexpected end of JSON input
    at D:\python\ByStrategy\backend\node_modules\node-fetch\lib\index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async OpenAPI.makeRequest (D:\python\ByStrategy\backend\node_modules\@tinkoff\invest-openapi-js-sdk\build\OpenAPI.cjs.js:273:19)
    at async Promise.all (index 0)
    at async Object.getCandlesAllTrackedInstrument (D:\python\ByStrategy\backend\src\api\time-frame\controllers\time-frame.js:174:34)
    at async Object.candles (D:\python\ByStrategy\backend\src\api\time-frame\controllers\time-frame.js:47:23)
    at async returnBodyMiddleware (D:\python\ByStrategy\backend\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:52:18)
    at async policiesMiddleware (D:\python\ByStrategy\backend\node_modules\@strapi\strapi\lib\services\server\policy.js:24:5)
    at async serve (D:\python\ByStrategy\backend\node_modules\koa-static\index.js:59:5)
    at async returnBodyMiddleware (D:\python\ByStrategy\backend\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:52:18)
    at async policiesMiddleware (D:\python\ByStrategy\backend\node_modules\@strapi\strapi\lib\services\server\policy.js:24:5)
    at async D:\python\ByStrategy\backend\node_modules\@strapi\strapi\lib\middlewares\body.js:58:9
    at async D:\python\ByStrategy\backend\node_modules\@strapi\strapi\lib\middlewares\logger.js:25:5
    at async D:\python\ByStrategy\backend\node_modules\@strapi\strapi\lib\middlewares\powered-by.js:16:5
    at async cors (D:\python\ByStrategy\backend\node_modules\@koa\cors\index.js:107:16)
    at async D:\python\ByStrategy\backend\node_modules\@strapi\strapi\lib\middlewares\errors.js:13:7
    at async session (D:\python\ByStrategy\backend\node_modules\koa-session\index.js:41:7)
    at async D:\python\ByStrategy\backend\node_modules\@strapi\strapi\lib\services\metrics\middleware.js:29:5

**Comment by AlexanderVolkovTCS** [comment]
https://tinkoff.github.io/investAPI/eol_v1/  к сожалению, поддержка старой версии закончилась.
