### ISSUE TITLE
Ошибка стрима сделок

### ISSUE THREAD

**Issue by PavelVlasenko** [Tinkoff/investAPI#5]
После подключения к стриму сделок, в течении 1 мин происходит ошибка и после этого сделки не приходят.
Используется java клиент для подключения.
io.grpc.StatusRuntimeException: UNAVAILABLE: upstream request timeout
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:442)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
	
	
	
Код клиента стрима выглядит: 
```
        Metadata header = new Metadata();
        Metadata.Key<String> key =
                Metadata.Key.of("Authorization", Metadata.ASCII_STRING_MARSHALLER);
        header.put(key, "Bearer  TOKEN");

        ManagedChannel channel = ManagedChannelBuilder
                .forAddress("invest-public-api.tinkoff.ru", 443)
                .build();


        OrdersStreamServiceGrpc.OrdersStreamServiceStub stub = OrdersStreamServiceGrpc.newStub(channel);
        stub = MetadataUtils.attachHeaders(stub, header);


        stub.tradesStream(TradesStreamRequest.newBuilder().build(), new StreamObserver<TradesStreamResponse>() {
            @Override
            public void onNext(TradesStreamResponse value) {
                log.info("{}", value);
            }

            @Override
            public void onError(Throwable t) {
                log.error("Error ", t);
            }

            @Override
            public void onCompleted() {
                log.info("Completed");
            }
        });

```

**Comment by malyginvv** [comment]
Добрый день!
Попробуйте сейчас, стримы должен работать стабильнее.

**Comment by AlexanderVolkovTCS** [comment]
Проблема решена, если что-то не так- то переоткройте тикет.
